In [ ]:
import pandas as pd


value_n_list = ['Andrew','Phillip','John', 'Enrique']
print(value_n_list)
value_w_list =[50,  78,   91.5, 77]
value_h_list =[1.76,  1.87,  1.69,  1.71]
data_dict = {"name": value_n_list,
             "weight":value_w_list,
             "height":value_h_list}

print(data_dict)
df = pd.DataFrame(data_dict)
print(df)

df

['Andrew', 'Phillip', 'John', 'Enrique']
{'name': ['Andrew', 'Phillip', 'John', 'Enrique'], 'weight': [50, 78, 91.5, 77], 'height': [1.76, 1.87, 1.69, 1.71]}
      name  weight  height
0   Andrew    50.0    1.76
1  Phillip    78.0    1.87
2     John    91.5    1.69
3  Enrique    77.0    1.71

      name  weight  height
0   Andrew    50.0    1.76
1  Phillip    78.0    1.87
2     John    91.5    1.69
3  Enrique    77.0    1.71

In [ ]:
df['BMI'] = df['weight'] / (df['height'] ** 2)
df

      name  weight  height        BMI
0   Andrew    50.0    1.76  16.141529
1  Phillip    78.0    1.87  22.305471
2     John    91.5    1.69  32.036693
3  Enrique    77.0    1.71  26.332889

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   weight  4 non-null      float64
 2   height  4 non-null      float64
 3   BMI     4 non-null      float64
dtypes: float64(3), object(1)
memory usage: 260.0+ bytes

In [ ]:
df.shape

(4, 4)

In [ ]:
df.describe()

          weight    height        BMI
count   4.000000  4.000000   4.000000
mean   74.125000  1.757500  24.204145
std    17.389532  0.080571   6.695548
min    50.000000  1.690000  16.141529
25%    70.250000  1.705000  20.764485
50%    77.500000  1.735000  24.319180
75%    81.375000  1.787500  27.758840
max    91.500000  1.870000  32.036693

In [ ]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
weight,4.0,74.125000,17.389532,50.000000,70.250000,77.50000,81.37500,91.500000
height,4.0,1.757500,0.080571,1.690000,1.705000,1.73500,1.78750,1.870000
BMI,4.0,24.204145,6.695548,16.141529,20.764485,24.31918,27.75884,32.036693

In [ ]:
df.describe(include="O")

          name
count        4
unique       4
top     Andrew
freq         1

In [ ]:
df.describe(include="all")

          name     weight    height        BMI
count        4   4.000000  4.000000   4.000000
unique       4        NaN       NaN        NaN
top     Andrew        NaN       NaN        NaN
freq         1        NaN       NaN        NaN
mean       NaN  74.125000  1.757500  24.204145
std        NaN  17.389532  0.080571   6.695548
min        NaN  50.000000  1.690000  16.141529
25%        NaN  70.250000  1.705000  20.764485
50%        NaN  77.500000  1.735000  24.319180
75%        NaN  81.375000  1.787500  27.758840
max        NaN  91.500000  1.870000  32.036693

In [ ]:
import math

s=50+78+91.5
promedio1=s/3
promedio1
n=3
v= ((50-promedio1)**2+(78-promedio1)**2+(91.5-promedio1)**2)/n-1
raiz=math.sqrt(v)
raiz

17.254629008536295

In [ ]:
import math

numero = 25
raiz_cuadrada = math.sqrt(numero)
print(f"La raíz cuadrada de {numero} es {raiz_cuadrada}")

numero2 = 91.5
raiz_cuadrada2 = math.sqrt(numero2)
print(f"La raíz cuadrada de {numero2} es {raiz_cuadrada2}")

In [2]:
import gradio as gr

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text")
demo.launch()

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://2560525f27fff90c75.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

In [3]:
import gradio as gr

def calculator(num1, operation, num2):
    if operation == '+':
        return num1 + num2
    elif operation == '-':
        return num1 - num2
    elif operation == '*':
        return num1 * num2
    elif operation == '/':
        if num2 == 0:
            return "Error: División por cero"
        return num1 / num2

calculator_demo = gr.Interface(
    fn=calculator,
    inputs=[
        gr.Number(label="Primer Número"),
        gr.Dropdown(["+", "-", "*", "/"], label="Operación"),
        gr.Number(label="Segundo Número")
    ],
    outputs="text",
    title="Calculadora Sencilla",
    description="Introduce dos números y selecciona una operación."
)

calculator_demo.launch()

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://daf90caa0bd40b7bdc.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)